### ISSUE TITLE
咨询框架源代码(c++)

### ISSUE THREAD

**Issue by PorUna-byte** [decaf-lang/minidecaf#3]
你好，我是哈尔滨工业大学的一名本科生，最近在网站 https://decaf-lang.github.io/minidecaf-tutorial/ 上看到贵系的编译课程指导，想自我尝试一下这门课程的实验部分，希望从中学到知识。
但是我无法获得框架源代码，似乎需要从清华的代码托管平台上获取，所以我在github上搜索框架源代码，最终找到的只有各位助教写好的已经能通过测试用例的代码。
我想问一下您能提供一下 https://decaf-lang.github.io/minidecaf-tutorial/ 该网站上所用到的框架的源代码吗？我想按照这个指导自己去实现一个能通过测试用例的编译器 minidecaf。 谢谢！！！

**Comment by namasikanam** [comment]
很抱歉，2021-2022 年度秋季学期的 start-code 经课程组讨论后决定不予开源。

我个人建议你可以参考助教的代码，从零开始自己写一个hhh

btw 这个仓库里的实现其实是 2020-2021 年秋季学期的参考实现，与最新的 tutorial 有些许出入，不过应该问题不大hhh
